### ISSUE TITLE
1.15.2 Client crash looking at Screen on server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [McJtyMods/RFToolsUtility#33]
I am working on a 1.15.2 pack and just updated RFTools Utility to 1.15-2.1.6. After logging on to my test server, I looked at the RFTools Screen and the client crashed.

- Linux Mint 19.3
- Minecraft 1.15.2
- Forge 1.15.2-31.2.36
- mcjtylib-1.15-4.1.5
- rftoolsbase-1.15-1.1.4
- rftoolsbuilder-1.15-2.1.6
- rftoolspower-1.15-2.2.2
- rftoolsstorage-1.15-1.1.7
- rftoolsutility-1.15-2.1.6

https://paste.ee/p/Nn3g8

**Comment by ClaudiusMinimus** [comment]
I just rolled rftoolsutility back to 1.15-2.1.3-beta and it still crashed, so I reverted all your mods and it runs fine

mcjtylib-1.15-4.1.1-beta
rftoolsbase-1.15-1.1.1-beta
rftoolsbuilder-1.15-2.1.3-beta
rftoolspower-1.15-2.1.1-beta
rftoolsstorage-1.15-1.1.4-beta
rftoolsutility-1.15-2.1.3-beta

**Comment by McJty** [comment]
You cannot just update RFToolsUtility alone. You must update all of them to latest

**Comment by ClaudiusMinimus** [comment]
I updated all of them to your latest versions.

**Comment by McJty** [comment]
I know what the problem is. Will fix shortly

**Comment by McJty** [comment]
Should be fixed now. You'll have to update all my mods

**Comment by ClaudiusMinimus** [comment]
I just updated the group and the client crashed. This error:

> Failed to load class mcjty.rftoolsutility.RFToolsUtility
java.lang.NoClassDefFoundError: mcjty/lib/base/ModBase

- mcjtylib-1.15-4.1.6
- rftoolsbase-1.15-1.1.5
- rftoolsbuilder-1.15-2.1.7
- rftoolscontrol-1.15-3.0.6
- rftoolspower-1.15-2.2.3
- rftoolsstorage-1.15-1.1.8
- rftoolsutility-1.15-2.1.6
- xnet-1.15-2.1.9

https://paste.ee/p/aPFb1

**Comment by McJty** [comment]
You didn't update RFTools Utility. That's at 2.1.8 right now

**Comment by ClaudiusMinimus** [comment]
Oops!

**Comment by ClaudiusMinimus** [comment]
The client loaded just fine after the RFTools Utility 2.1.8 update, but when I copied the updates from the client folder to the server it crashed on startup.

- mcjtylib-1.15-4.1.6
- rftoolsbase-1.15-1.1.5
- rftoolsbuilder-1.15-2.1.7
- rftoolscontrol-1.15-3.0.6
- rftoolspower-1.15-2.2.3
- rftoolsstorage-1.15-1.1.8
- rftoolsutility-1.15-2.1.8
- xnet-1.15-2.1.9

https://pastebin.com/jvBHghaf

Thank you very much for your quick responses! I really appreciate that!
CM

**Comment by McJty** [comment]
Literally a minute ago I released an update of all my mods for 1.15 which should fix this problem. Let me know if it helps. Unfortunatelly you'll have to update all of them again. Sorry for the trouble

**Comment by ClaudiusMinimus** [comment]
Was able to download them all, except for [XNet 1.15-2.1.10](https://www.curseforge.com/minecraft/mc-mods/xnet/files/3043247) - there is an error on the page. I will try again in the morning as it is very late here and I'm going to bed now. 
Thanks and good night,
CM

**Comment by McJty** [comment]
Hmm. I could download it just fine

**Comment by ClaudiusMinimus** [comment]
Seems to work great. Thanks!
